# Generated by Django 6.0.2 on 2026-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='target_weight',
            field=models.FloatField(blank=True, help_text='Target Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='fitnessprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Current Weight in kg', null=True),
        ),
    ]
