# Generated by Django 6.0.2 on 2026-03-12 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15)),
                ('meal_name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('protein', models.FloatField(help_text='in grams')),
                ('carbs', models.FloatField(help_text='in grams')),
                ('fats', models.FloatField(help_text='in grams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('workouts_done', models.PositiveIntegerField(default=0)),
                ('current_weight', models.FloatField(help_text='in kg')),
                ('streak', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
