# Generated by Django 6.0.2 on 2026-03-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result_stat', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('brief', models.TextField()),
                ('is_gain', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
