# Generated by Django 6.0.2 on 2026-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/after/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/before/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='full_story',
            field=models.TextField(blank=True, default=''),
        ),
    ]
